<main>
    <h2>
        <?= $pageTitle; ?>
    </h2>
    <!-- Votre formulaire ici -->
     <form method="post" action="controllers\user-form.php" >
        <input type="email" name="email" id="email" placeholder="votre email" required>
        <input type="password" name="password" id="password" placeholder="votre mot de passe" required>
        <button type="submit">validé</button>
     </form>
</main>